stages:
 - build

build_image:
  image: docker:latest
  services:
  - docker:dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/kuylar/lighttube .
    - docker push registry.gitlab.com/kuylar/lighttube:latest

# todo: push to docker hub